name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build container image
      uses: docker/build-push-action@v3
      with:
          context: .
          push: false
          file: ./Dockerfile
